type SMPPErrorCode = {
  commandStatusName: string
  hexValue: string
  value: number
  description: string
}

// https://smpp.org/smpp-error-codes.html
export const smppErrorCodes: SMPPErrorCode[] = [
  {
    commandStatusName: 'ESME_ROK',
    hexValue: '00000000',
    value: 0,
    description: 'No Error',
  },
  {
    commandStatusName: 'ESME_RINVMSGLEN',
    hexValue: '00000001',
    value: 1,
    description: 'Message Length is invalid',
  },
  {
    commandStatusName: 'ESME_RINVCMDLEN',
    hexValue: '00000002',
    value: 2,
    description: 'Command Length is invalid',
  },
  {
    commandStatusName: 'ESME_RINVCMDID',
    hexValue: '00000003',
    value: 3,
    description: 'Invalid Command ID',
  },
  {
    commandStatusName: 'ESME_RINVBNDSTS',
    hexValue: '00000004',
    value: 4,
    description: 'Incorrect BIND Status for given command',
  },
  {
    commandStatusName: 'ESME_RALYBND',
    hexValue: '00000005',
    value: 5,
    description: 'ESME Already in Bound State',
  },
  {
    commandStatusName: 'ESME_RINVPRTFLG',
    hexValue: '00000006',
    value: 6,
    description: 'Invalid Priority Flag',
  },
  {
    commandStatusName: 'ESME_RINVREGDLVFLG',
    hexValue: '00000007',
    value: 7,
    description: 'Invalid Registered Delivery Flag',
  },
  {
    commandStatusName: 'ESME_RSYSERR',
    hexValue: '00000008',
    value: 8,
    description: 'System Error',
  },
  {
    commandStatusName: 'ESME_RINVSRCADR',
    hexValue: '0000000A',
    value: 10,
    description: 'Invalid Source Address',
  },
  {
    commandStatusName: 'ESME_RINVDSTADR',
    hexValue: '0000000B',
    value: 11,
    description: 'Invalid Destination Address',
  },
  {
    commandStatusName: 'ESME_RINVMSGID',
    hexValue: '0000000C',
    value: 12,
    description: 'Message ID is invalid',
  },
  {
    commandStatusName: 'ESME_RBINDFAIL',
    hexValue: '0000000D',
    value: 13,
    description: 'Bind Failed',
  },
  {
    commandStatusName: 'ESME_RINVPASWD',
    hexValue: '0000000E',
    value: 14,
    description: 'Invalid Password',
  },
  {
    commandStatusName: 'ESME_RINVSYSID',
    hexValue: '0000000F',
    value: 15,
    description: 'Invalid System ID',
  },
  {
    commandStatusName: 'ESME_RCANCELFAIL',
    hexValue: '00000011',
    value: 17,
    description: 'Cancel SM Failed',
  },
  {
    commandStatusName: 'ESME_RREPLACEFAIL',
    hexValue: '00000013',
    value: 19,
    description: 'Replace SM Failed',
  },
  {
    commandStatusName: 'ESME_RMSGQFUL',
    hexValue: '00000014',
    value: 20,
    description: 'Message Queue Full',
  },
  {
    commandStatusName: 'ESME_RINVSERTYP',
    hexValue: '00000015',
    value: 21,
    description: 'Invalid Service Type',
  },
  {
    commandStatusName: 'ESME_RINVNUMDESTS',
    hexValue: '00000033',
    value: 51,
    description: 'Invalid number of destinations',
  },
  {
    commandStatusName: 'ESME_RINVDLNAME',
    hexValue: '00000034',
    value: 52,
    description: 'Invalid Distribution List name',
  },
  {
    commandStatusName: 'ESME_RINVDESTFLAG',
    hexValue: '00000040',
    value: 64,
    description: 'Destination flag is invalid (submit_multi)',
  },
  {
    commandStatusName: 'ESME_RINVSUBREP',
    hexValue: '00000042',
    value: 66,
    description:
      'Invalid submit with replace request (i.e. submit_sm with replace_if_present_flag set)',
  },
  {
    commandStatusName: 'ESME_RINVESMCLASS',
    hexValue: '00000043',
    value: 67,
    description: 'Invalid esm_class field data',
  },
  {
    commandStatusName: 'ESME_RCNTSUBDL',
    hexValue: '00000044',
    value: 68,
    description: 'Cannot Submit to Distribution List',
  },
  {
    commandStatusName: 'ESME_RSUBMITFAIL',
    hexValue: '00000045',
    value: 69,
    description: 'submit_sm or submit_multi failed',
  },
  {
    commandStatusName: 'ESME_RINVSRCTON',
    hexValue: '00000048',
    value: 72,
    description: 'Invalid Source address TON',
  },
  {
    commandStatusName: 'ESME_RINVSRCNPI',
    hexValue: '00000049',
    value: 73,
    description: 'Invalid Source address NPI',
  },
  {
    commandStatusName: 'ESME_RINVDSTTON',
    hexValue: '00000050',
    value: 80,
    description: 'Invalid Destination address TON',
  },
  {
    commandStatusName: 'ESME_RINVDSTNPI',
    hexValue: '00000051',
    value: 81,
    description: 'Invalid Destination address NPI',
  },
  {
    commandStatusName: 'ESME_RINVSYSTYP',
    hexValue: '00000053',
    value: 83,
    description: 'Invalid system_type field',
  },
  {
    commandStatusName: 'ESME_RINVREPFLAG',
    hexValue: '00000054',
    value: 84,
    description: 'Invalid replace_if_present flag',
  },
  {
    commandStatusName: 'ESME_RINVNUMMSGS',
    hexValue: '00000055',
    value: 85,
    description: 'Invalid number of messages',
  },
  {
    commandStatusName: 'ESME_RTHROTTLED',
    hexValue: '00000058',
    value: 88,
    description: 'Throttling error (ESME has exceeded allowed message limits)',
  },
  {
    commandStatusName: 'ESME_RINVSCHED',
    hexValue: '00000061',
    value: 97,
    description: 'Invalid Scheduled Delivery Time',
  },
  {
    commandStatusName: 'ESME_RINVEXPIRY',
    hexValue: '00000062',
    value: 98,
    description: 'Invalid message validity period (Expiry time)',
  },
  {
    commandStatusName: 'ESME_RINVDFTMSGID',
    hexValue: '00000063',
    value: 99,
    description: 'Predefined Message Invalid or Not Found',
  },
  {
    commandStatusName: 'ESME_RX_T_APPN',
    hexValue: '00000064',
    value: 100,
    description: 'ESME Receiver Temporary App Error Code',
  },
  {
    commandStatusName: 'ESME_RX_P_APPN',
    hexValue: '00000065',
    value: 101,
    description: 'ESME Receiver Permanent App Error Code',
  },
  {
    commandStatusName: 'ESME_RX_R_APPN',
    hexValue: '00000066',
    value: 102,
    description: 'ESME Receiver Reject Message Error Code',
  },
  {
    commandStatusName: 'ESME_RQUERYFAIL',
    hexValue: '00000067',
    value: 103,
    description: 'query_sm request failed',
  },
  {
    commandStatusName: 'ESME_RINVTLVSTREAM',
    hexValue: '000000C0',
    value: 192,
    description: 'Error in the optional part of the PDU Body',
  },
  {
    commandStatusName: 'ESME_RTLVNOTALLWD',
    hexValue: '000000C1',
    value: 193,
    description: 'TLV not allowed',
  },
  {
    commandStatusName: 'ESME_RINVTLVLEN',
    hexValue: '000000C2',
    value: 194,
    description: 'Invalid TLV Length',
  },
  {
    commandStatusName: 'ESME_RMISSINGTLV',
    hexValue: '000000C3',
    value: 195,
    description: 'Missing TLV',
  },
  {
    commandStatusName: 'ESME_RINVTLVVAL',
    hexValue: '000000C4',
    value: 196,
    description: 'Invalid TLV Value',
  },
  {
    commandStatusName: 'ESME_RDELIVERYFAILURE',
    hexValue: '000000FE',
    value: 254,
    description: 'Transaction Delivery Failure',
  },
  {
    commandStatusName: 'ESME_RUNKNOWNERR',
    hexValue: '000000FF',
    value: 255,
    description: 'Unknown Error',
  },
  {
    commandStatusName: 'ESME_RSERTYPUNAUTH',
    hexValue: '00000100',
    value: 256,
    description: 'ESME Not authorised to use specified service_type',
  },
  {
    commandStatusName: 'ESME_RPROHIBITED',
    hexValue: '00000101',
    value: 257,
    description: 'ESME Prohibited from using specified operation',
  },
  {
    commandStatusName: 'ESME_RSERTYPUNAVAIL',
    hexValue: '00000102',
    value: 258,
    description: 'Specified service_type is unavailable',
  },
  {
    commandStatusName: 'ESME_RSERTYPDENIED',
    hexValue: '00000103',
    value: 259,
    description: 'Specified service_type is denied',
  },
  {
    commandStatusName: 'ESME_RINVDCS',
    hexValue: '00000104',
    value: 260,
    description: 'Invalid Data Coding Scheme',
  },
  {
    commandStatusName: 'ESME_RINVSRCADDRSUBUNIT',
    hexValue: '00000105',
    value: 261,
    description: 'Source Address Subunit is Invalid',
  },
  {
    commandStatusName: 'ESME_RINVDSTADDRSUBUNIT',
    hexValue: '00000106',
    value: 262,
    description: 'Destination Address Subunit is Invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTFREQINT',
    hexValue: '00000107',
    value: 263,
    description: 'Broadcast Frequency Interval is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTALIAS_NAME',
    hexValue: '00000108',
    value: 264,
    description: 'Broadcast Alias Name is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTAREAFMT',
    hexValue: '00000109',
    value: 265,
    description: 'Broadcast Area Format is invalid',
  },
  {
    commandStatusName: 'ESME_RINVNUMBCAST_AREAS',
    hexValue: '0000010A',
    value: 266,
    description: 'Number of Broadcast Areas is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTCNTTYPE',
    hexValue: '0000010B',
    value: 267,
    description: 'Broadcast Content Type is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTMSGCLASS',
    hexValue: '0000010C',
    value: 268,
    description: 'Broadcast Message Class is invalid',
  },
  {
    commandStatusName: 'ESME_RBCASTFAIL',
    hexValue: '0000010D',
    value: 269,
    description: 'broadcast_sm operation failed',
  },
  {
    commandStatusName: 'ESME_RBCASTQUERYFAIL',
    hexValue: '0000010E',
    value: 270,
    description: 'query_broadcast_sm operation failed',
  },
  {
    commandStatusName: 'ESME_RBCASTCANCELFAIL',
    hexValue: '0000010F',
    value: 271,
    description: 'cancel_broadcast_sm operation failed',
  },
  {
    commandStatusName: 'ESME_RINVBCASTREP',
    hexValue: '00000110',
    value: 272,
    description: 'Number of Repeated Broadcasts is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTSRVGRP',
    hexValue: '00000111',
    value: 273,
    description: 'Broadcast Service Group is invalid',
  },
  {
    commandStatusName: 'ESME_RINVBCASTCHANIND',
    hexValue: '00000112',
    value: 274,
    description: 'Broadcast Channel Indicator is invalid',
  },
]
